### ISSUE TITLE
Form Home_plus problem

### ISSUE THREAD

**Issue by fujitsuJackyChow** [fujitsu-hk-bas/FormEditorPage#7]
Disable dorp down value
CoverageDetails-"house type"
If "Low-Rise House" is selected, the dropdown value of "sum insured" need to disable "HK$1,250,000.00" & "HK$1,500,000.00"

**Comment by ivan114** [comment]
May need "Choice Filter" function to dynamic control available choices depends on values

**Comment by ivan114** [comment]
duplicated #6
